# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipdata',
            old_name='anonimity',
            new_name='anonymity',
        ),
    ]
