# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170615_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdata',
            name='HTTPS',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
    ]
